### ISSUE TITLE
Questions about usage

### ISSUE THREAD

**Issue by abirafdirp** [niftydigits/ftrack-s3-accessor#3]
Hi there,

First off I would like to say that I have limited knowledge with ftrack.
We are currently using Gdrive for the Centralized storage location, but the speed is too slow and we're looking for alternatives.
Thanks to you for this plugin though I have some problems that seems trivial...

#### Via plugins directory
I have set up all the necessary env vars so that the plugins is detected and loaded verified in the ftrack logs. I have installed all the deps i.e. boto3 et al to my machine's default Python interpreter. But ftrack-connect uses its own Python interpreter, so when I try to Publish a file, it raises exception that boto3 is not found, so how do I install boto3 to ftrack-connect's Python?

#### Via start_ftrack_with_s3.py
I assume this script listen for events and ftrack-connect also need to be run at the same time. But when I try to publish a file, the script does nothing. Does the script listen for the Publish file event? what things that I overlooked? Does ftrack-connect also need to be run?

Thanks for your time!

**Comment by iwootten** [comment]
This plugin can be used in a variety of ways.

The start ftrack with s3 example is probably the best way to get started. Clone the repo, create a virtualenv with the requirements listed in the pyproject.toml file installed (boto3, ftrack-python-api and ftrack-action-handler) and set the environment variables. This route won't require ftrack connect to be running for the plugins to work. If the env vars are set correctly, you should see "registering s3 accessor" logged out when you invoke the script.

Alternatively, you can set the FTRACK_EVENT_PLUGIN_PATH to point to the plugins subfolder, but you'll also need to modify s3_location.py to import the dependencies too.

Another option is to move the location plugin to an appropriate folder structure and add it to ftracks plugins dir. See here for an example of what a plugin structure is like : https://ftrack-connect.rtd.ftrack.com/en/stable/developing/tutorial/adding_a_location.html

If you add the transfer components action to the plugins directory, you'll also get that loaded and ready to use when you click the actions menu next to a component.
